SET CLIENT_ENCODING TO 'utf8';
/*
DROP TABLE IF EXISTS takeoff;
DROP TABLE IF EXISTS inventory_receipts;
DROP TABLE IF EXISTS glass;
DROP TABLE IF EXISTS projects;
*/

DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY,
    username varchar,
    password_hash varchar,
    email varchar,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS profiles (
	profile_id varchar,
	profile_name varchar,
	linear_density numeric(10,3),
	PRIMARY KEY (profile_id)
)
/*
CREATE TABLE IF NOT EXISTS projects (
	project_id varchar,
	PRIMARY KEY (project_id)
);

CREATE TABLE IF NOT EXISTS glass (
	glass_id varchar,
	glass_name varchar,
	PRIMARY KEY (glass_id)
)

CREATE TABLE IF NOT EXISTS inventory_receipts (
    receipt_id varchar,
	PRIMARY KEY (receipt_id)
);

CREATE TABLE IF NOT EXISTS takeoff (
	project_id varchar,
	material_id varchar references materials(material_id),
	item_count int,
	PRIMARY KEY (project_id)
);
*/